export const TOGGLE_PRODUCT_CODE = 'TOGGLE_PRODUCT_CODE';
export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
export const CLEAR_CURRENT_PRODUCT = 'CLEAR_CURRENT_PRODUCT';
export const INITIALIZE_CURRENT_PRODUCT = 'INITIALIZE_CURRENT_PRODUCT';

export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const LOAD_PRODUCT_SUCCES = 'LOAD_PRODUCT_SUCCES';
export const LOAD_PRODUCT_FAIL = 'LOAD_PRODUCT_FAIL';
